### ISSUE TITLE
"Error null HTTP 500" when sending message

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#94]
I sent a message to the whole group, and got an error message. The log in the Android client showed this:

```
Sat Aug 05 19:30:58 GMT+01:00 2017: Error null
HTTP 500 
retrofit2.adapter.rxjava.HttpException: HTTP 500 
	at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:43)
	at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:38)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1$1.call(OperatorSubscribeOn.java:85)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

The message was received fine, and I can see it after refreshing (click back and then click the group chat again).

**Comment by zond** [comment]
Sounds like temporary server error (and after the message was persisted no
less!). Unless we know what the stacktrace on the server was it'll be
hard/impossible to fix.

**Comment by tttppp** [comment]
Ok, I'm afk at the moment, but I'll have a look at the logs when I get chance. I may just close this as "won't fix".

**Comment by zond** [comment]
Sure, unless it happens a lot there are higher priorities I guess :)

**Comment by tttppp** [comment]
I don't think this is specific enough to fix.
